version: 2

models:
  - name: data_services_job_dim
    description: Validate Unique keys
    columns:
      - name: etl_job_key
        description: Primary key
        tests:
          - unique
          - not_null
      - name: ds_repo_key
        tests: 
          - not_null
      - name: job_name
        tests: 
          - not_null
      - name:  "(cast(ds_repo_key as varchar) || '-' || job_name)"
        tests: 
          - unique

  - name: data_services_repo_dim
    description: Validate Unique Keys
    columns:
      - name: ds_repo_key
        description: Primary key
        tests:
          - unique
          - not_null
      - name: ds_repo_name
        description: Unique key
        tests:
          - unique
          - not_null

  - name: data_services_job_exec_fact_error
    description: Failed Audit - Any rows on this table constitute an audit failure
    tests:
      - audit_failed